# Test locally built image
version: '3.8'

services:
  # Test the fixed local image
  ai-knowledge-manager:
    image: ai-knowledge-manager-test:latest
    container_name: ai-knowledge-manager-test
    ports:
      - "8080:7040"  # Access at http://localhost:8080
    volumes:
      - ai-knowledge-data:/app/data          # Persistent data storage
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ChatCompleteSettings__VectorStore__Provider=Qdrant        # Use Qdrant
      - ChatCompleteSettings__VectorStore__Qdrant__Host=qdrant    # Reference Qdrant service
      - ChatCompleteSettings__VectorStore__Qdrant__Port=6334      # gRPC port
      - Logging__LogLevel__Default=Information
      # API keys - set these via .env file or command line
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7040/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - ai-services

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-test
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - ai-services
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  ai-knowledge-data:
    driver: local
    name: ai-knowledge-data-test
  qdrant-data:
    driver: local
    name: qdrant-data-test

networks:
  ai-services:
    driver: bridge
    name: ai-services-network-test